# Generated by Django 2.0.6 on 2020-02-17 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='课程封面')),
                ('desc', models.CharField(max_length=300, verbose_name='课程描述')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], default='cj', max_length=2, verbose_name='难度')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('learn_time', models.IntegerField(default=0, verbose_name='学习时长（分钟数）')),
                ('category', models.CharField(default='后端', max_length=100, verbose_name='课程类别')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('detail', models.TextField(verbose_name='课程详情')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否为轮播图')),
                ('before_know', models.CharField(default='', max_length=300, verbose_name='课前须知')),
                ('teacher_tell', models.CharField(default='', max_length=300, verbose_name='老师告诉你能学到什么')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('notice', models.CharField(default='暂无公告', max_length=300, verbose_name='课程公告')),
                ('course_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Organizationinfo', verbose_name='所属机构')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资料名称')),
                ('download', models.FileField(upload_to='courses/resource/%Y/%m', verbose_name='资料下载')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courseinfo', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程资料',
                'verbose_name_plural': '课程资料',
            },
        ),
        migrations.CreateModel(
            name='Lession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='章名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Courseinfo', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程章节',
                'verbose_name_plural': '课程章节',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='小节/视频名称')),
                ('url', models.URLField(default='http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4', verbose_name='播放地址')),
                ('learn_time', models.IntegerField(default=0, verbose_name='视频时长（分钟数）')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lession', verbose_name='章')),
            ],
            options={
                'verbose_name': '小节/视频',
                'verbose_name_plural': '小节/视频',
            },
        ),
        migrations.CreateModel(
            name='CourseBanner',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.courseinfo',),
        ),
    ]
